server:
  port: 8081
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: <db_url>
    username: <db_username>
    password: <db_password>
    sslrootcert: classpath:ssl/root.crt
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate.sql: DEBUG

# AWS S3
access:
  key:
    id: <aws_s3_key_id>
    secret: <aws_s3_key_secret>

s3:
  region:
    name: ap-northeast-2
  bucket:
    name: bk-sims-storage
    url: https://bk-sims-storage.s3.ap-northeast-2.amazonaws.com/

application:
  security:
    jwt:
      secret-key: <jwt_secret_key>
      expiration: 86400000
      refresh-token:
        expiration: 604800000

springdoc:
  api-docs:
    path: /doc/api-docs
  swagger-ui:
    path: /doc/swagger
