server:
  port: 8081

spring:
  config:
    import: file:env.properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB


logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate.sql: DEBUG

# AWS S3
access:
  key:
    id: ${AWS_ACCESS}
    secret: ${AWS_SECRET}

s3:
  region:
    name: ${S3_REGION}
  bucket:
    name: ${S3_BUCKET}
    url: ${S3_BUCKET_URL}

springdoc:
  api-docs:
    path: /doc/api-docs
  swagger-ui:
    path: /doc/swagger