server:
  port: 8081

spring:
  config:
    import: optional:file:env.properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    url: ${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate.sql: DEBUG

# AWS S3
access:
  key:
    id: ${AWS_ACCESS}
    secret: ${AWS_SECRET}

s3:
  region:
    name: ${S3_REGION}
  bucket:
    name: ${S3_BUCKET}
    url: ${S3_BUCKET_URL}

application:
  security:
    jwt:
      secret-key: c4d0b52d59e24b276649b9a0e98d12c7dd86193bbcb2748a8734831c0d539c9f
      expiration: 86400000
      refresh-token:
        expiration: 604800000

springdoc:
  api-docs:
    path: /doc/api-docs
  swagger-ui:
    path: /doc/swagger
