name: Update Cockroach DB

env:
  DATABASE_DIR: ./database
  CERT_DIR: ./backend/src/main/resources/ssl

on:
  push:
    branches: ["main"]
    paths: ["database/init-cockroach.sql", ".github/workflows/db-update.yml"]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CockroachDB client
        run: |
          sudo apt-get update
          sudo apt-get install cockroach
          sudo mkdir -p /usr/local/lib/cockroach
          sudo cp -i cockroach-v23.2.4.linux-amd64/lib/libgeos.so /usr/local/lib/cockroach/
          sudo cp -i cockroach-v23.2.4.linux-amd64/lib/libgeos_c.so /usr/local/lib/cockroach/

      - name: Update application properties
        run: |
          /usr/local/bin/cockroach sql --url 'postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.COCKROACH_DB }}/bk_sims?sslmode=verify-full&sslrootcert=${{ env.CERT_DIR }}/root.crt' -f ${{ env.DATABASE_DIR }}/init-cockroach.sql
